namespace FluentTerminal.Models.Enums
{
    public enum Command
    {
        ToggleWindow,
        NextTab,
        PreviousTab,
        NewTab,
        NewWindow,
        ConfigurableNewTab,
        ConfigurableNewWindow,
        NewSshTab,
        NewSshWindow,
        NewCustomCommandTab, 
        NewCustomCommandWindow,
        SavedSshNewTab,
        SavedSshNewWindow,
        ChangeTabTitle,
        CloseTab,
        ShowSettings,
        Copy,
        Paste,
        PasteWithoutNewlines,
        Search,
        ToggleFullScreen,
        SelectAll,
        Clear,
        SwitchToTerm1,
        SwitchToTerm2,
        SwitchToTerm3,
        SwitchToTerm4,
        SwitchToTerm5,
        SwitchToTerm6,
        SwitchToTerm7,
        SwitchToTerm8,
        SwitchToTerm9,
        DuplicateTab
    }
}