// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Messages/protos/TerminalDataMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FluentTerminal.Models.Messages.Protobuf {

  /// <summary>Holder for reflection information generated from Messages/protos/TerminalDataMessage.proto</summary>
  public static partial class TerminalDataMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Messages/protos/TerminalDataMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TerminalDataMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilNZXNzYWdlcy9wcm90b3MvVGVybWluYWxEYXRhTWVzc2FnZS5wcm90bxIC",
            "ZnQiMgoGUGJHdWlkEhMKC2d1aWRfcGFydF8xGAEgASgEEhMKC2d1aWRfcGFy",
            "dF8yGAIgASgEIjcKDFRlcm1pbmFsRGF0YRIYCgRndWlkGAEgASgLMgouZnQu",
            "UGJHdWlkEg0KBWJ5dGVzGAIgASgMQiqqAidGbHVlbnRUZXJtaW5hbC5Nb2Rl",
            "bHMuTWVzc2FnZXMuUHJvdG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FluentTerminal.Models.Messages.Protobuf.PbGuid), global::FluentTerminal.Models.Messages.Protobuf.PbGuid.Parser, new[]{ "GuidPart1", "GuidPart2" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FluentTerminal.Models.Messages.Protobuf.TerminalData), global::FluentTerminal.Models.Messages.Protobuf.TerminalData.Parser, new[]{ "Guid", "Bytes" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PbGuid : pb::IMessage<PbGuid> {
    private static readonly pb::MessageParser<PbGuid> _parser = new pb::MessageParser<PbGuid>(() => new PbGuid());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PbGuid> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FluentTerminal.Models.Messages.Protobuf.TerminalDataMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PbGuid() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PbGuid(PbGuid other) : this() {
      guidPart1_ = other.guidPart1_;
      guidPart2_ = other.guidPart2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PbGuid Clone() {
      return new PbGuid(this);
    }

    /// <summary>Field number for the "guid_part_1" field.</summary>
    public const int GuidPart1FieldNumber = 1;
    private ulong guidPart1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong GuidPart1 {
      get { return guidPart1_; }
      set {
        guidPart1_ = value;
      }
    }

    /// <summary>Field number for the "guid_part_2" field.</summary>
    public const int GuidPart2FieldNumber = 2;
    private ulong guidPart2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong GuidPart2 {
      get { return guidPart2_; }
      set {
        guidPart2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PbGuid);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PbGuid other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GuidPart1 != other.GuidPart1) return false;
      if (GuidPart2 != other.GuidPart2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (GuidPart1 != 0UL) hash ^= GuidPart1.GetHashCode();
      if (GuidPart2 != 0UL) hash ^= GuidPart2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GuidPart1 != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(GuidPart1);
      }
      if (GuidPart2 != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(GuidPart2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GuidPart1 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GuidPart1);
      }
      if (GuidPart2 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GuidPart2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PbGuid other) {
      if (other == null) {
        return;
      }
      if (other.GuidPart1 != 0UL) {
        GuidPart1 = other.GuidPart1;
      }
      if (other.GuidPart2 != 0UL) {
        GuidPart2 = other.GuidPart2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GuidPart1 = input.ReadUInt64();
            break;
          }
          case 16: {
            GuidPart2 = input.ReadUInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TerminalData : pb::IMessage<TerminalData> {
    private static readonly pb::MessageParser<TerminalData> _parser = new pb::MessageParser<TerminalData>(() => new TerminalData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TerminalData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FluentTerminal.Models.Messages.Protobuf.TerminalDataMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TerminalData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TerminalData(TerminalData other) : this() {
      guid_ = other.guid_ != null ? other.guid_.Clone() : null;
      bytes_ = other.bytes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TerminalData Clone() {
      return new TerminalData(this);
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 1;
    private global::FluentTerminal.Models.Messages.Protobuf.PbGuid guid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::FluentTerminal.Models.Messages.Protobuf.PbGuid Guid {
      get { return guid_; }
      set {
        guid_ = value;
      }
    }

    /// <summary>Field number for the "bytes" field.</summary>
    public const int BytesFieldNumber = 2;
    private pb::ByteString bytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Bytes {
      get { return bytes_; }
      set {
        bytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TerminalData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TerminalData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Guid, other.Guid)) return false;
      if (Bytes != other.Bytes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (guid_ != null) hash ^= Guid.GetHashCode();
      if (Bytes.Length != 0) hash ^= Bytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (guid_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Guid);
      }
      if (Bytes.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Bytes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (guid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Guid);
      }
      if (Bytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bytes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TerminalData other) {
      if (other == null) {
        return;
      }
      if (other.guid_ != null) {
        if (guid_ == null) {
          Guid = new global::FluentTerminal.Models.Messages.Protobuf.PbGuid();
        }
        Guid.MergeFrom(other.Guid);
      }
      if (other.Bytes.Length != 0) {
        Bytes = other.Bytes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (guid_ == null) {
              Guid = new global::FluentTerminal.Models.Messages.Protobuf.PbGuid();
            }
            input.ReadMessage(Guid);
            break;
          }
          case 18: {
            Bytes = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
